version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: zenithdb_sql
    volumes:
      - ./postgres:/var/lib/postgresql/data

  mongo:
    image: mongo:5
    restart: always
    container_name: zenithdb_mongo
    ports:
      - "27017:27017"
    environment:
      MONGODB_DATABASE: ${MONGO_DB}
    volumes:
      - ./mongo:/data/db